{"name": "test_login_user_with_issues[locked_out_user-secret_sauce-Sorry, this user has been locked out.]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/vn53xo7/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/vn53xo7/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:66:14)\n    at AndroidUiautomator2Driver.findElement (/Users/vn53xo7/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:13:12)", "trace": "self = <test_login.TestSignIn object at 0x104c7f050>, user = 'locked_out_user', password = 'secret_sauce', errormsg = 'Sorry, this user has been locked out.'\n\n    @pytest.mark.parametrize(\"user, password, errormsg\",\n                             [(\"\", \"\", \"Username is required\"),\n                              (\"locked_out_user\", \"secret_sauce\", \"Sorry, this user has been locked out.\")])\n    def test_login_user_with_issues(self, user, password, errormsg):\n        login_page = LoginPage(self.driver)\n>       login_page.login(user, password)\n\ntest/test_login.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPOM/login.py:29: in login\n    self.type_email(user)\nPOM/login.py:20: in type_email\n    self.find(self.username_input).send_keys(email)\nutilities/baseClass.py:16: in find\n    return self.driver.find_element(*locator)\nvenv/lib/python3.11/site-packages/appium/webdriver/webdriver.py:409: in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\nvenv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x104c44350>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"An element could not be located on the page u...tomator2Driver.findElement (/Users/vn53xo7/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:13:12)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        try:\n            payload_dict = json.loads(payload)\n        except (json.JSONDecodeError, TypeError):\n            return\n        if not isinstance(payload_dict, dict):\n            return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at AndroidUiautomator2Driver.findElOrEls (/Users/vn53xo7/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\nE           at processTicksAndRejections (node:internal/process/task_queues:96:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/vn53xo7/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:66:14)\nE           at AndroidUiautomator2Driver.findElement (/Users/vn53xo7/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:13:12)\n\nvenv/lib/python3.11/site-packages/appium/webdriver/errorhandler.py:122: NoSuchElementException"}, "parameters": [{"name": "user", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}, {"name": "errormsg", "value": "'Sorry, this user has been locked out.'"}], "start": 1686516999540, "stop": 1686516999673, "uuid": "7354c607-3e21-4d31-a667-749bfa73ef4a", "historyId": "7ccd7299ae53bcf97946e1bf6ac467be", "testCaseId": "b7b2b8804ad6016478cd3229692aa3b8", "fullName": "test.test_login.TestSignIn#test_login_user_with_issues", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('driver_setup')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSignIn"}, {"name": "host", "value": "M-X14WXMDVVX-9.local"}, {"name": "thread", "value": "74908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login"}]}